### PR TITLE
Update dependency for npm audit

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?
package-lock.json included dependency with audit problem

### How did I fix it?
Update affected dependency

### How to test it?
run `npm audit`

### Review checklist

* The PR resolves #INSERT_ISSUE_NUMBER
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by fchavant** [comment]
@shuse2 looks like this broken the [Functional WS tests](https://jenkins.lisk.io/blue/organizations/jenkins/lisk-sdk-framework/detail/PR-3760/6/pipeline/310).

**Comment by shuse2** [comment]
@fchavant Unfortunately, thats unstable tests which is not related to this PR

**Comment by ManuGowda** [comment]
@shuse2 i tried to fix this issue with just running `npm audit fix` and it only changed 
```
-                "lerna": "3.13.2",
+               "lerna": "3.14.1",
```

**Comment by shuse2** [comment]
@ManuGowda `npm aduit` only runs on root level, so it run one by one
Lerna doesnt support audit yet

**Comment by ManuGowda** [comment]
> @ManuGowda `npm aduit` only runs on root level, so it run one by one
> Lerna doesnt support audit yet

hmmm ok.. good to know 👍

**Pull request merged**
