### PR TITLE
Lisk core upgrade to latest version using Lisk commander failed - Closes #4037

### LINKED ISSUE #4037: Lisk core upgrade to latest version using Lisk commander failed
### Expected behavior
Lisk commander should upgrade to the latest version without any optional parameters.
### Actual behavior
Lisk Commander failed to upgrade with default latest version parameter option. It requires `--release-url` to be passed in order to make it work.

**Note:** install also has the same issue, requiring `--release-url` when `--lisk-version` is specified which should be optional
### Steps to reproduce
- Install Lisk core `2.0.0` using commander `lisk core:install --version=2.0.0 lisk-mainnet`
- Upgrade to `2.0.1` `lisk core:upgrade lisk-mainnet`
- The second step will fail to upgrade
### Which version(s) does this affect? (Environment, OS, etc...)
2.2.0

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?
Commands lisk core `install` and `upgrade` failed due to missing default release URL
### How did I solve it?
Handled default release URL for `install` and `upgrade`
### How to manually test it?
```
cd commander;
npm run build;
./bin/run core:install --network=testnet --no-snapshot --lisk-version=2.0.0-rc.0 lisk-testnet
./bin/run core:status lisk-testnet
./bin/run core:stop lisk-testnet
./bin/run core:start lisk-testnet
./bin/run core:restart lisk-testnet
./bin/run core:upgrade --lisk-version=2.0.1-rc.0 lisk-testnet
./bin/run core:status
./bin/run core:logs lisk-testnet
```
### Review checklist

- [x] The PR resolves #4037 
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [x] Documentation has been added/updated

### CODE REVIEW

**Comment by fchavant** [comment]
@ManuGowda the following fails without any clear error message:
```
lisk@ams3-francois-commander-01:~$ ~/lisk/bin/lisk core:install --network=testnet --no-snapshot foo
  ❯ Install Lisk Core testnet instance as foo
    ✖ Prepare Install Options
      → Cannot read property '0' of null
      Validate root user, flags, prerequisites
      Download Lisk Core Release and Blockchain Snapshot
      Extract Lisk Core
      Register Lisk Core
      Create Database and restore Lisk Blockchain Snapshot
 ›   Error: {"context":{}}
```

**Comment by fchavant** [comment]
Those work as expected however:
```
~/lisk/bin/lisk core:install --network=testnet --no-snapshot --lisk-version=2.0.0-rc.0 bar
~/lisk/bin/lisk core:upgrade bar
```

```
~/lisk/bin/lisk core:install --network=testnet --no-snapshot --lisk-version=2.0.0-rc.0 baz
~/lisk/bin/lisk core:upgrade --lisk-version=2.0.1-rc.0 baz
```

**Comment by shuse2** [comment]
Same for `./bin/run core:install --network=testnet lisk-testnet`

**Comment by ManuGowda** [comment]
Thank you @shuse2 @fchavant for testing I have fixed the issue here is the new build https://jenkins.lisk.io/job/lisk-qa/job/lisk-commander-build-tag/36/

**Pull request merged**
