### PR TITLE
Add authorize endpoint to chain connector plugin

### LINKED ISSUE #8484: Implement authorize RPC endpoint to enable CCU signing
### Description

Introduce `authorize` RPC to take password as param and decrypt the encrypted object instead of passing password in the config.

**Similar Implementation:** https://github.com/LiskHQ/lisk-sdk/blob/1d5d18d2b46129d0f33da1c56220b73248cd251e/framework-plugins/lisk-framework-report-misbehavior-plugin/src/endpoint.ts#L39

### Acceptance Criteria

- Should have unit tests

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #8484 

### How was it solved?

- Add `authorize` endpoint 
- Remove `password` config from chain connector plugin

### How was it tested?

- Register chain connector plugin in example app
```
// package.json needs to be updated to include chain connector plugin as well
export const registerPlugins = (app: Application): void => {
	app.registerPlugin(new ChainConnectorPlugin(), { loadAsChildProcess: true });
};
```
- Run the app
- `./bin/run endpoint:invoke chainConnector_authorize '{"password": "1234", "enable": false}' `

### CODE REVIEW

**Review by ishantiw — COMMENTED** [review]
Can we also log the error message here to let the user know that there is no key enabled

https://github.com/LiskHQ/lisk-sdk/blob/1d583f49ff295609034779489202ab0152d4804d/framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts#L226

**Comment by shuse2** [comment]
@ishantiw in that line, `_submitCCU` is already called in the try-catch, so if the key is not enabled, it will always be logged before that line?

**Comment by ishantiw** [comment]
@shuse2 Oh I thought we are throwing error when key not enabled, I think its better to throw error and be logged here [lisk-sdk/framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts](https://github.com/LiskHQ/lisk-sdk/blob/1d583f49ff295609034779489202ab0152d4804d/framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts#L226) because if we only return the [next line](https://github.com/LiskHQ/lisk-sdk/blob/1d583f49ff295609034779489202ab0152d4804d/framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts#L222) will assume that the CCU was sent and will save the last sent CCM where it was not really sent to the other chain. So in this case we can raise error and it will retry to create the CCU next time with the CCM that was not sent earlier

**Comment by shuse2** [comment]
@ishantiw good point! updated the PR to throw and log 🙇

**Review by ishantiw — APPROVED** [review]

**Review by Phanco — APPROVED** [review]

**Pull request merged**
