### PR TITLE
Update genesis block tests

### LINKED ISSUE #7237: Add missing integration test for "genesis block"
**Description**
- if verifyStateRoot() returns true, processing of the genesis block continues
- if verifyStateRoot() returns false, genesis block is discarded

> The stateRoot set in the genesis block does not correspond to the state generated during "Genesis state initialization" and "Genesis state finalization"

- verifyValidatorsHash() returns true, processing of the genesis block continues
- verifyValidatorsHash() returns false, genesis block is discarded 

> validatorHash  is not according to the info stored in the BFT module (retrieved by bft.getBFTParameters() )

**Which version(s) does this affect? (Environment, OS, etc...)**
development

### LINKED ISSUE #8136: Unit test review genesis block processing (LIP 0060)
## Header

- Test for [`signature` property](https://github.com/LiskHQ/lisk-sdk/blob/de09b745a369c0970db7a8db2e5980534a1a036a/elements/lisk-chain/test/unit/block_header.spec.ts#L287): The requirement is NOT that the property is empty. Instead, the property should not even exist. So, this test should fail **due the existence** of the `signature` property. Moreover, genesis block validation should also fail if it has a signature property set to empty bytes.
- A test is missing where `generatorAddress` is NOT equal to `0x00..00` in which case the processing is expected to fail.
- Tests for the property `impliesMaxPrevotes` are missing (for both values `True` and `False`).
- Test for invalid `maxHeightGenerated` is missing.
- Tests for invalid `aggregateCommit.height`, `aggregateCommit.aggregationBits` and `aggregateCommit.certificateSignature` are missing.
- There is no test for the `stateRoot` property. In particular, there is no test that expects that genesis block processing fails if the value of `header.stateRoot` in incorrect.
- If [these tests](https://github.com/LiskHQ/lisk-sdk/blob/de09b745a369c0970db7a8db2e5980534a1a036a/framework/test/unit/engine/consensus/consensus.spec.ts#L1019-L1041) do not cover the `eventRoot` for genesis blocks (I'm not sure about it), then the tests for `eventRoot` are missing.
- If [these tests](https://github.com/LiskHQ/lisk-sdk/blob/de09b745a369c0970db7a8db2e5980534a1a036a/framework/test/unit/engine/consensus/consensus.spec.ts#L933-L980) do not cover the `validatorsHash` for genesis blocks (I'm not sure about it), then the tests for `validatorsHash ` are missing.

## Assets

- There seems to be no test to ensure that block processing fails if `asset.module` does not refer to a registered module for any asset `asset` in the block.

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #8136 and resolves #7237 

### How was it solved?

- Add missing genesis block related tests
- Created another issue #8439 , which should be resolved in release branch

### How was it tested?

N/A

### CODE REVIEW

**Review by AndreasKendziorra — CHANGES_REQUESTED** [review]
The following point from #8136 is still unaddressed:

> There is no test for the stateRoot property. In particular, there is no test that expects that genesis block processing fails if the value of header.stateRoot in incorrect.

**Comment by AndreasKendziorra** [comment]
I left two additional review comments for a file, but they got somehow lost. So, I repeat them here:

- As stated in #8136, the tests for `signature` are still not correct.
- Test for valid `impliesMaxPrevotes` (value must be `true`) is missing. More generally, a test for a valid genesis block missing.

**Comment by shuse2** [comment]
@AndreasKendziorra 
Added valid genesis block case and merged the other PR into development, so the error message should be resolved on the branch already.

For the signature property, I made a comment on the issue 🙇

**Comment by shuse2** [comment]
@AndreasKendziorra i think i missed the comment. Added the relevant test 👍

**Review by AndreasKendziorra — APPROVED** [review]

**Review by has5aan — APPROVED** [review]

**Pull request merged**
