### PR TITLE
Update NFT module with additional checks and LIP updates

### LINKED ISSUE #8580: Update NFT and token module with additional checks and LIP updates
### Description

Add/remove checks and update logic as specified in [LIP PR](https://github.com/LiskHQ/lips/pull/367)

### Acceptance Criteria

Add/update unit tests per the new logic

### Additional Information
@mjerkov should be added as a reviewer for this issue

### PR DESCRIPTION
**Pull request by Incede**
### What was the problem?

This PR partially resolves #8580 

### How was it solved?

Update NFT module as specified

### How was it tested?

Added unit tests

### CODE REVIEW

**Review by shuse2 — CHANGES_REQUESTED** [review]
Token module change should be a different PR targeting release/6.0.0 branch 🙏 
Assuming above, token module part is not reviewed

**Review by mjerkov — APPROVED** [review]
Looks good, as per [comment ](https://github.com/LiskHQ/lisk-sdk/pull/8635#pullrequestreview-1492751607) I reviewed only the NFT part.

**Comment by mjerkov** [comment]
I see that some [tests](https://github.com/LiskHQ/lisk-sdk/actions/runs/5347110810/jobs/9695337935?pr=8635) are failing, do you have idea why that may be?

**Comment by Incede** [comment]
> I see that some [tests](https://github.com/LiskHQ/lisk-sdk/actions/runs/5347110810/jobs/9695337935?pr=8635) are failing, do you have idea why that may be?

yes, the tests were failing due to the incorrect setup of `context` - the chain id in a command context is supposed to be the same as the own chain id but for some test cases it was not. I fixed it now.

**Review by shuse2 — APPROVED** [review]

**Pull request merged**
